# Generated by Django 2.0.13 on 2020-08-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200820_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchtweetslocationmodel',
            name='userloc',
            field=models.IntegerField(),
        ),
    ]
